### PR TITLE
Environment support

### PR DESCRIPTION
**Pull request by erikh**
This supports propagating the environment to subcommands.

### CODE REVIEW

**Comment by rendon** [comment]
Thanks @erikh for contributing, I'm reviewing your changes.

**Comment by rendon** [comment]
@erikh All your PRs are merged, thanks for your contributions. I've fixed a couple of merge conflicts, please verify all your changes were applied correctly.

**Comment by erikh** [comment]
ok, can't now, but I will this evening and submit any changes needed.

Thanks!

**Comment by erikh** [comment]
@rendon things are looking great here, thanks again for the great lib!

**Comment by rendon** [comment]
Great!

**Pull request merged**
