### PR TITLE
Add a go.mod

### PR DESCRIPTION
**Pull request by erikh**
Signed-off-by: Erik Hollensbe <github@hollensbe.org>

### CODE REVIEW

**Comment by erikh** [comment]
Also if you could tag a release according to #5 I'd really appreciate it. I'm going to patch up my go.mod in my fork and tag that for now. Please fire back when you've done this so I can switch to the official lib. Thanks!

**Comment by rendon** [comment]
Hi @erikh , I'm kind of busy these days, it might take some time. Pull requests are welcome, though.

**Comment by erikh** [comment]
No worries; but this is a pull request :)

**Comment by rendon** [comment]
I didn't realize it was a PR 😅. Thank you.

**Pull request merged**
